### ISSUE TITLE
Some feedback

### ISSUE THREAD

**Issue by Tomay0** [BeansPlusPlus/Website#1]
Just some comments on how to improve the code you've written + fix some bugs:

### CSS

I would suggest you move all your styling code out into a separate `.css` file. 

Currently, you already have `<link rel="stylesheet" href="main.css">` in your `<head>`, which is good. But you should provide the CSS file with this.

All styling stuff you have in the <head> wrapped in `<style>` tags should go in here.

For example, `main.css` should look something like this:

```css
h1 {
          height: 40px;
          width: 500px;
          border-radius: 100px;
          box-sizing: border-box;
          background-blend-mode: color-burn;
          text-align: center;
          /* Not sure if you want the text colour gray here or the right border colour to be gray? Either way you've done it wrong here
          border-right: 
          color: darkslategray;   */
          background-color: palevioletred;
}

h2 {
          background-color: blanchedalmond;
          width: 180px;
          border-radius: 100px;
          color: darkgoldenrod;
}


/* ... etc */
```

### Meta tags

`<meta name="A MC server for creatives and minigames" content="Playtime">` isn;t a valid meta tag. If you want this to describe the description of the webpage it should look something like `<meta name="description" content="A MC server for creatives and minigames">`

Meta tags aren't really important if you're just learning. I think they're used by search engines or something. But you can read about them [here](https://developers.google.com/search/docs/crawling-indexing/special-tags#:~:text=meta%20tags%20are%20HTML%20tags,DOCTYPE%20html%3E)

### Float right

The `<float: right>` here doesn't actually do anything here: `<float: right><h3>Hang out with some nerds!</h3></float:>` 

If you actually want it to float to the right you can do something like: 
`<h3 style="float: right">Hang out with some nerds!</h3>`
although I don't think it will give the results you expect, as it will just cause the text to "float" above everything on the right side of the screen. I would suggest you style it with `text-align` instead.

### Style using classes

Take this line for example:

```html
<p>
            <em> Welcome to our BEANS MC server, a cutting edge playground for adults who like games and creating stuff and things. 
            <br> Owned by Isaac Irvine. <br>Web design by the Min Iles </em>
</p>
``` 
and you've styled it like this:

```css
p {
        border-style: solid;
        border-radius: 100px;
        border-width: thin;
        border-style: hidden;
        background-color: lavenderblush;
}
```

The problem with this is that you've forced all paragraph tags to look like this when you might want to have paragraphs around the place that do not have this styling.

Usually, we would put a class on a tag to achieve this effect. In this example, I've wrapped the paragraph in a `<div>`, with a class I've given it.

```html
<div class="light-paragraph">
    <p>
            <em> Welcome to our BEANS MC server, a cutting edge playground for adults who like games and creating stuff and things. 
            <br> Owned by Isaac Irvine. <br>Web design by the Min Iles </em>
    </p>
</div>
```

```css
.light-paragraph { /* The dot signifies a class */
        border-style: solid;
        border-radius: 100px;
        border-width: thin;
        border-style: hidden;
        background-color: lavenderblush;
}
```

You don't need to attach a class to a div. Any tag can be given a class. But a `<div>` is great because it can be used to separate multiple elements into a "container".

### Other random mistakes

This line is useless and doesn't do anything lol:

```html
<div> 
        <style> class="h2" 
        </style> </div>
```

Same with this: You already have made your `h2` bold in your styling:

```html
<style> Floatright;
            Text-type: bold; </style>
```

This line can be simplified:

```html
<img: href: src= "Screenshot%202023-02-22%20213827.png"></img:> 
<!-- Change to the below. The : is not needed and href: does not do anything. -->
<img src="Screenshot%202023-02-22%20213827.png" />
```

Also please indent the code properly it's really hard to read lmao
